import type { Metadata } from "next";

import { LessonShell } from "@/components/lesson-shell";
import { OperatingCashFlowLearning } from "@/components/operating-cash-flow-learning";
import cashFlowContent from "@/content/cash-flow-lessons/aapl-operating-cash-flow-fy2025.json";
import {
  FinPathApiError,
  getCompanyCashFlowStatement,
  type CompanyCashFlowStatement,
} from "@/lib/api";
import {
  OperatingCashFlowDataError,
  validateCashFlowStatementForLesson,
} from "@/lib/operating-cash-flow";

export const metadata: Metadata = {
  title: "Learn Operating Cash Flow",
  description: "Connect Apple's Net Income to cash generated by operating activities.",
};

export const dynamic = "force-dynamic";

export default async function OperatingCashFlowLessonPage() {
  let cashFlowStatement: CompanyCashFlowStatement | null = null;
  let dataError: string | null = null;

  try {
    cashFlowStatement = await getCompanyCashFlowStatement(
      cashFlowContent.ticker,
      cashFlowContent.fiscalYear,
    );
    validateCashFlowStatementForLesson(cashFlowStatement.statement, {
      fiscalYear: cashFlowContent.fiscalYear,
      accession: cashFlowContent.accession,
    });
  } catch (error) {
    cashFlowStatement = null;
    dataError =
      error instanceof FinPathApiError || error instanceof OperatingCashFlowDataError
        ? error.message
        : "The FinPath API is not available. Start FastAPI and try again.";
  }

  return (
    <LessonShell
      conceptId="operating-cash-flow"
      example="Apple Inc. · FY2025 · SEC 10-K"
    >
      {cashFlowStatement ? (
        <OperatingCashFlowLearning cashFlowStatement={cashFlowStatement} />
      ) : (
        <div className="data-empty-state profit-data-empty" role="status">
          <div className="data-empty-state__value" aria-hidden="true">—</div>
          <div>
            <strong>Operating Cash Flow data is not available yet</strong>
            <p>{dataError}</p>
            <p>FinPath will not replace missing or mismatched SEC facts with hard-coded values.</p>
          </div>
        </div>
      )}
    </LessonShell>
  );
}
