import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import {
  cashFlowLineMap,
  OperatingCashFlowDataError,
  validateCashFlowStatementForLesson,
} from "../src/lib/operating-cash-flow.ts";


const readSource = (relativePath) =>
  readFile(new URL(`../src/${relativePath}`, import.meta.url), "utf8");

const lineValues = [
  ["net-income", "starting-line", 112_010_000_000],
  ["depreciation-and-amortization", "non-cash-adjustment", 11_698_000_000],
  ["share-based-compensation-expense", "non-cash-adjustment", 12_863_000_000],
  ["other", "non-cash-adjustment", -89_000_000],
  ["accounts-receivable-net", "operating-timing-adjustment", -6_682_000_000],
  ["vendor-non-trade-receivables", "operating-timing-adjustment", -347_000_000],
  ["inventories", "operating-timing-adjustment", 1_400_000_000],
  ["other-current-and-non-current-assets", "operating-timing-adjustment", -9_197_000_000],
  ["accounts-payable", "operating-timing-adjustment", 902_000_000],
  ["other-current-and-non-current-liabilities", "operating-timing-adjustment", -11_076_000_000],
  ["cash-generated-by-operating-activities", "final-total", 111_482_000_000],
];

function makeStatement() {
  return {
    fiscalYear: 2025,
    startDate: "2024-09-29",
    endDate: "2025-09-27",
    currency: "USD",
    form: "10-K",
    filedAt: "2025-10-31",
    accession: "0000320193-25-000079",
    sourceUrl:
      "https://www.sec.gov/Archives/edgar/data/320193/000032019325000079/0000320193-25-000079-index.htm",
    sections: [
      {
        id: "operating",
        lines: lineValues.map(([id, role, value]) => ({
          id,
          role,
          value,
          taxonomyTag: `fixture-${id}`,
          taxonomyLabel: `Fixture ${id}`,
        })),
      },
      { id: "investing", lines: [] },
      { id: "financing", lines: [] },
    ],
    cashMovement: {},
  };
}

test("validates the exact FY2025 operating cash reconciliation", () => {
  const statement = makeStatement();

  assert.doesNotThrow(() =>
    validateCashFlowStatementForLesson(statement, {
      fiscalYear: 2025,
      accession: "0000320193-25-000079",
    }),
  );
  const lines = cashFlowLineMap(statement.sections[0].lines);
  assert.equal(lines.get("net-income").value, 112_010_000_000);
  assert.equal(
    lines.get("cash-generated-by-operating-activities").value,
    111_482_000_000,
  );
  assert.equal(
    statement.sections[0].lines.slice(0, -1).reduce((sum, line) => sum + line.value, 0),
    statement.sections[0].lines.at(-1).value,
  );
});

test("rejects wrong filing identity, order, arithmetic, and provenance", () => {
  const cases = [
    () => ({ ...makeStatement(), accession: "0000320193-24-000123" }),
    () => {
      const statement = makeStatement();
      statement.sections[0].lines.reverse();
      return statement;
    },
    () => {
      const statement = makeStatement();
      statement.sections[0].lines[1].value -= 1;
      return statement;
    },
    () => ({ ...makeStatement(), sourceUrl: "https://example.com/filing" }),
    () => ({
      ...makeStatement(),
      sourceUrl:
        "https://www.sec.gov/Archives/edgar/data/999999/000032019325000079/0000320193-25-000079-index.htm",
    }),
  ];

  for (const createStatement of cases) {
    assert.throws(
      () =>
        validateCashFlowStatementForLesson(createStatement(), {
          fiscalYear: 2025,
          accession: "0000320193-25-000079",
        }),
      OperatingCashFlowDataError,
    );
  }
});

test("reviewed content keeps exact labels and reported-vs-display boundaries", async () => {
  const content = JSON.parse(
    await readSource("content/cash-flow-lessons/aapl-operating-cash-flow-fy2025.json"),
  );
  const labels = Object.values(content.lines).map((line) => line.reportedLabel);

  assert.deepEqual(labels, [
    "Net income",
    "Depreciation and amortization",
    "Share-based compensation expense",
    "Other",
    "Accounts receivable, net",
    "Vendor non-trade receivables",
    "Inventories",
    "Other current and non-current assets",
    "Accounts payable",
    "Other current and non-current liabilities",
    "Cash generated by operating activities",
  ]);
  assert.equal(content.verification.statementName, "Consolidated Statements of Cash Flows");
  assert.match(content.boundary, /not.*year-end cash balance/i);
  assert.match(content.limitation, /does not tell you.*long-term assets/i);
  assert.doesNotMatch(JSON.stringify(content), /112\.010|111\.482|11\.698|6\.682/);
  assert.ok(content.sources.every((source) => new URL(source.url).protocol === "https:"));
});

test("lesson uses four progressive sections and marks progress only after the final check", async () => {
  const [component, content] = await Promise.all([
    readSource("components/operating-cash-flow-learning.tsx"),
    readSource("content/cash-flow-lessons/aapl-operating-cash-flow-fy2025.json").then(JSON.parse),
  ]);

  assert.match(component, /data-cash-section="profit-not-cash"/);
  assert.match(component, /data-cash-section="cash-bridge"/);
  assert.match(component, /data-cash-section="why-different"/);
  assert.match(component, /data-cash-section="check-difference"/);
  assert.match(component, /See more Apple adjustments/);
  assert.equal(content.firstQuestion.hint, "Choose one. This is practice, not a score.");
  assert.equal(content.finalQuestion.hint, "Choose one. This is practice, not a score.");
  assert.match(component, /markExplored\(\["operating-cash-flow"\]\)/);
  assert.equal(
    (component.match(/markExplored\(\["operating-cash-flow"\]\)/g) ?? []).length,
    1,
  );
  assert.match(component, /<EvidenceInspector[^]*evidence=\{operatingCashEvidence\}/);
  assert.doesNotMatch(component, /free cash flow|cash available to spend/i);
});

test("OCF evidence is reported and uses the reusable million-to-billion inspector", async () => {
  const [component, evidence] = await Promise.all([
    readSource("components/operating-cash-flow-learning.tsx"),
    readSource("lib/evidence.ts"),
  ]);

  assert.match(component, /id: "operating-cash-flow", label: "Operating Cash Flow"/);
  assert.match(evidence, /\| "revenue"/);
  assert.match(evidence, /\| "net-income"/);
  assert.match(evidence, /\| "operating-cash-flow"/);
  assert.match(component, /buildReportedEvidence/);
  assert.doesNotMatch(component, /build.*DerivedEvidence/);
});
