"use client";

import { useState, type FormEvent } from "react";

import { EvidenceInspector } from "@/components/evidence-inspector";
import { useLearningProgress } from "@/components/learning-progress-provider";
import cashFlowContent from "@/content/cash-flow-lessons/aapl-operating-cash-flow-fy2025.json";
import type {
  CashFlowStatementLineId,
  CompanyCashFlowStatement,
} from "@/lib/api";
import {
  buildReportedEvidence,
  buildReviewedPresentation,
  reportedFactFromStatementLine,
  type FinancialStatementLineId,
} from "@/lib/evidence";
import { cashFlowLineMap } from "@/lib/operating-cash-flow";


type OperatingCashFlowLearningProps = {
  cashFlowStatement: CompanyCashFlowStatement;
};

type LineCopy = { reportedLabel: string; helper: string };

const lineCopy = cashFlowContent.lines as Record<
  CashFlowStatementLineId,
  LineCopy
>;
const reviewedLabels = Object.fromEntries(
  Object.entries(lineCopy).map(([id, copy]) => [id, copy.reportedLabel]),
) as Partial<Record<FinancialStatementLineId, string>>;

const exactBillions = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
  minimumFractionDigits: 3,
  maximumFractionDigits: 3,
});

function formatBillions(value: number): string {
  return `${exactBillions.format(Math.abs(value) / 1_000_000_000)}B`;
}

function formatSignedBillions(value: number): string {
  const formatted = formatBillions(value);
  return value < 0 ? `(${formatted})` : formatted;
}

export function OperatingCashFlowLearning({
  cashFlowStatement,
}: OperatingCashFlowLearningProps) {
  const { markExplored } = useLearningProgress();
  const { statement, dataStatus } = cashFlowStatement;
  const lines = cashFlowLineMap(statement.lines);
  const netIncome = lines.get("net-income");
  const depreciation = lines.get("depreciation-and-amortization");
  const accountsReceivable = lines.get("accounts-receivable-net");
  const operatingCash = lines.get("cash-generated-by-operating-activities");
  const [revealedSection, setRevealedSection] = useState(1);
  const [firstChoice, setFirstChoice] = useState<string | null>(null);
  const [reviewedFirstChoice, setReviewedFirstChoice] = useState<string | null>(null);
  const [finalChoice, setFinalChoice] = useState<string | null>(null);
  const [reviewedFinalChoice, setReviewedFinalChoice] = useState<string | null>(null);

  if (!netIncome || !depreciation || !accountsReceivable || !operatingCash) {
    return null;
  }

  const reviewedOperatingCash = buildReviewedPresentation({
    statement,
    content: {
      fiscalYear: cashFlowContent.fiscalYear,
      startDate: cashFlowContent.startDate,
      endDate: cashFlowContent.endDate,
      form: cashFlowContent.form as "10-K" | "10-K/A",
      filedAt: cashFlowContent.filedAt,
      accession: cashFlowContent.accession,
      statementName: cashFlowContent.verification.statementName,
      labels: reviewedLabels,
    },
    lineId: "cash-generated-by-operating-activities",
    contextLineIds: statement.lines.map((line) => line.id),
  });
  const operatingCashEvidence = buildReportedEvidence({
    metric: { id: "operating-cash-flow", label: "Operating Cash Flow" },
    company: cashFlowStatement.company,
    currency: statement.currency,
    fact: reportedFactFromStatementLine(
      statement,
      "cash-generated-by-operating-activities",
    ),
    dataStatus,
    reviewedPresentation: reviewedOperatingCash,
  });

  function reviewFirstQuestion(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (firstChoice) setReviewedFirstChoice(firstChoice);
  }

  function reviewFinalQuestion(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!finalChoice) return;
    setReviewedFinalChoice(finalChoice);
    markExplored(["operating-cash-flow"]);
  }

  function finalFeedback(choice: string): string {
    if (choice === cashFlowContent.finalQuestion.supportedChoiceId) {
      return cashFlowContent.finalQuestion.supportedFeedback;
    }
    return choice === "net-income"
      ? cashFlowContent.finalQuestion.netIncomeFeedback
      : cashFlowContent.finalQuestion.cashBalanceFeedback;
  }

  return (
    <section className="cash-lesson" aria-labelledby="cash-lesson-title">
      <header className="cash-lesson__header">
        <p className="eyebrow">Operating Cash Flow · guided cash bridge</p>
        <h2 id="cash-lesson-title">{cashFlowContent.title}</h2>
        <p>
          Apple reported {formatBillions(netIncome.value)} of Net Income. Follow
          how that accounting result connects to cash generated by operating
          activities.
        </p>
        <p className="profit-lesson__period">
          FY{statement.fiscalYear} · {statement.currency} · year ended {statement.endDate}
          {" · "}
          <a href={statement.sourceUrl} rel="noreferrer" target="_blank">
            SEC {statement.form} ↗
          </a>
        </p>
      </header>

      <p className="sr-only" aria-live="polite">
        {revealedSection} of 4 learning sections visible.
      </p>

      <section
        className="cash-section cash-section--question"
        data-cash-section="profit-not-cash"
        aria-labelledby="profit-not-cash-title"
      >
        <p className="cash-section__number">01 · Profit is not cash</p>
        <div className="cash-starting-value">
          <span>Net Income</span>
          <strong>{formatBillions(netIncome.value)}</strong>
          <small>Apple reported · accounting result</small>
        </div>
        <form onSubmit={reviewFirstQuestion}>
          <fieldset>
            <legend id="profit-not-cash-title">
              {cashFlowContent.firstQuestion.prompt}
            </legend>
            <p>{cashFlowContent.firstQuestion.hint}</p>
            <div className="cash-choice-list">
              {cashFlowContent.firstQuestion.choices.map((choice) => (
                <label key={choice.id}>
                  <input
                    checked={firstChoice === choice.id}
                    name="profit-is-cash"
                    onChange={() => {
                      setFirstChoice(choice.id);
                      setReviewedFirstChoice(null);
                    }}
                    type="radio"
                    value={choice.id}
                  />
                  <span>{choice.label}</span>
                </label>
              ))}
            </div>
          </fieldset>
          <button disabled={!firstChoice} type="submit">Check my reasoning</button>
        </form>
        {reviewedFirstChoice ? (
          <div className="cash-feedback" role="status">
            <p>
              {reviewedFirstChoice === cashFlowContent.firstQuestion.supportedChoiceId
                ? cashFlowContent.firstQuestion.supportedFeedback
                : cashFlowContent.firstQuestion.unsupportedFeedback}
            </p>
            {revealedSection === 1 ? (
              <button onClick={() => setRevealedSection(2)} type="button">
                Follow the cash bridge
              </button>
            ) : null}
          </div>
        ) : null}
      </section>

      {revealedSection >= 2 ? (
        <section
          className="cash-section"
          data-cash-section="cash-bridge"
          aria-labelledby="cash-bridge-title"
        >
          <p className="cash-section__number">02 · Follow the cash bridge</p>
          <div className="cash-bridge-layout">
            <div className="cash-bridge" aria-labelledby="cash-bridge-title">
              <div>
                <span id="cash-bridge-title">Net Income</span>
                <strong>{formatBillions(netIncome.value)}</strong>
                <small>Apple reported · Income Statement</small>
              </div>
              <div className="cash-bridge__connector">
                <span aria-hidden="true">↓</span>
                <strong>Non-cash + operating timing adjustments</strong>
              </div>
              <div>
                <span>Cash generated by operating activities</span>
                <strong>{formatBillions(operatingCash.value)}</strong>
                <small>Apple reported · Cash Flow Statement</small>
              </div>
            </div>
            <aside className="cash-learning-trace" aria-label="Learning Trace">
              <p><span aria-hidden="true" /> Learning Trace</p>
              <h3>Profit and operating cash are related, but they are not the same measure.</h3>
              <p>
                Apple starts this operating reconciliation with Net Income, then
                reports non-cash items and changes in operating assets and liabilities.
              </p>
              <strong>{cashFlowContent.boundary}</strong>
            </aside>
          </div>
          {revealedSection === 2 ? (
            <button className="cash-continue" onClick={() => setRevealedSection(3)} type="button">
              Why can they differ?
            </button>
          ) : null}
        </section>
      ) : null}

      {revealedSection >= 3 ? (
        <section
          className="cash-section"
          data-cash-section="why-different"
          aria-labelledby="cash-difference-title"
        >
          <p className="cash-section__number">03 · Why can they differ?</p>
          <h3 id="cash-difference-title">Two ideas are enough for a first reading.</h3>
          <div className="cash-adjustment-examples">
            <article>
              <p className="eyebrow">Non-cash item</p>
              <h4>{lineCopy[depreciation.id].reportedLabel}</h4>
              <strong>+ {formatBillions(depreciation.value)}</strong>
              <p>
                Apple adds this back in the reconciliation. The expense reduced
                Net Income, but the same amount was not a current-period operating
                cash payment. That does not make the expense fake or unimportant.
              </p>
            </article>
            <article>
              <p className="eyebrow">Operating cash timing</p>
              <h4>{lineCopy[accountsReceivable.id].reportedLabel}</h4>
              <strong>− {formatBillions(accountsReceivable.value)}</strong>
              <p>
                Apple reports a negative operating-cash adjustment here. Revenue
                recognition and cash collection do not always happen at the same time.
              </p>
            </article>
          </div>

          <details className="cash-full-reconciliation">
            <summary>See more Apple adjustments</summary>
            <div>
              <p className="cash-reconciliation-note">
                Apple-reported lines · FY{statement.fiscalYear} · USD billions.
                These signed amounts reconcile Net Income to operating cash; they
                are not all cash payments.
              </p>
              <dl>
                {statement.lines.map((line) => (
                  <div data-role={line.role} key={line.id}>
                    <dt>
                      <strong>{lineCopy[line.id].reportedLabel}</strong>
                      <small>{lineCopy[line.id].helper}</small>
                    </dt>
                    <dd>{formatSignedBillions(line.value)}</dd>
                  </div>
                ))}
              </dl>
              <p>{cashFlowContent.verification.displayNote}</p>
              <a href={cashFlowContent.sources[0].url} rel="noreferrer" target="_blank">
                Open the filed statement ↗
              </a>
            </div>
          </details>

          {revealedSection === 3 ? (
            <button className="cash-continue" onClick={() => setRevealedSection(4)} type="button">
              Check the difference
            </button>
          ) : null}
        </section>
      ) : null}

      {revealedSection >= 4 ? (
        <section
          className="cash-section cash-section--question"
          data-cash-section="check-difference"
          aria-labelledby="cash-final-check-title"
        >
          <p className="cash-section__number">04 · Check the difference</p>
          <dl className="cash-comparison">
            <div><dt>Net Income</dt><dd>{formatBillions(netIncome.value)}</dd></div>
            <div><dt>Operating Cash Flow</dt><dd>{formatBillions(operatingCash.value)}</dd></div>
          </dl>
          <form onSubmit={reviewFinalQuestion}>
            <fieldset>
              <legend id="cash-final-check-title">
                {cashFlowContent.finalQuestion.prompt}
              </legend>
              <p>{cashFlowContent.finalQuestion.hint}</p>
              <div className="cash-choice-list">
                {cashFlowContent.finalQuestion.choices.map((choice) => (
                  <label key={choice.id}>
                    <input
                      checked={finalChoice === choice.id}
                      name="operating-cash-meaning"
                      onChange={() => {
                        setFinalChoice(choice.id);
                        setReviewedFinalChoice(null);
                      }}
                      type="radio"
                      value={choice.id}
                    />
                    <span>{choice.label}</span>
                  </label>
                ))}
              </div>
            </fieldset>
            <button disabled={!finalChoice} type="submit">Check my reasoning</button>
          </form>
          {reviewedFinalChoice ? (
            <div className="cash-completion" role="status">
              <p>{finalFeedback(reviewedFinalChoice)}</p>
              <EvidenceInspector
                evidence={operatingCashEvidence}
                id="operating-cash-flow-evidence"
              />
              <aside aria-labelledby="cash-limit-heading" className="cash-limitation">
                <p className="eyebrow" id="cash-limit-heading">What this cannot tell you</p>
                <p>{cashFlowContent.limitation}</p>
              </aside>
            </div>
          ) : null}
        </section>
      ) : null}


      <p className="profit-retrieved-note">
        Retrieved {new Date(dataStatus.retrievedAt).toLocaleString("en-MY", {
          timeZone: "Asia/Kuala_Lumpur",
        })}
        {dataStatus.state === "stale"
          ? " · SEC was unavailable, so FinPath is showing the last known public filing data."
          : ""}
      </p>
    </section>
  );
}
