import type { Metadata } from "next";
import Link from "next/link";

import { OperatingCashFlowLearning } from "@/components/operating-cash-flow-learning";
import cashFlowContent from "@/content/cash-flow-lessons/aapl-operating-cash-flow-fy2025.json";
import {
  FinPathApiError,
  getCompanyCashFlowStatement,
  type CompanyCashFlowStatement,
} from "@/lib/api";
import {
  OperatingCashFlowDataError,
  validateCashFlowStatementForLesson,
} from "@/lib/operating-cash-flow";


export const metadata: Metadata = {
  title: "Apple Operating Cash Flow",
  description:
    "Follow Apple's FY2025 reconciliation from Net Income to cash generated by operating activities.",
};

export const dynamic = "force-dynamic";

export default async function AppleOperatingCashFlowPage() {
  let cashFlowStatement: CompanyCashFlowStatement | null = null;
  let dataError: string | null = null;

  try {
    cashFlowStatement = await getCompanyCashFlowStatement(
      cashFlowContent.ticker,
      cashFlowContent.fiscalYear,
    );
    validateCashFlowStatementForLesson(cashFlowStatement.statement, {
      fiscalYear: cashFlowContent.fiscalYear,
      accession: cashFlowContent.accession,
    });
  } catch (error) {
    cashFlowStatement = null;
    if (
      error instanceof FinPathApiError ||
      error instanceof OperatingCashFlowDataError
    ) {
      dataError = error.message;
    } else {
      dataError = "The FinPath API is not available. Start FastAPI and try again.";
    }
  }

  return (
    <div className="company-shell profit-page-shell">
      <nav className="breadcrumb" aria-label="Breadcrumb">
        <Link href="/">Home</Link>
        <span aria-hidden="true">/</span>
        <span>Explore</span>
        <span aria-hidden="true">/</span>
        <Link href="/company/aapl">Apple Inc.</Link>
        <span aria-hidden="true">/</span>
        <strong>Operating Cash Flow</strong>
      </nav>

      <header className="company-header profit-company-header">
        <div>
          <p className="eyebrow">Company research</p>
          <h1>{cashFlowStatement?.company.name ?? "Apple Inc."}</h1>
          <p className="company-header__meta">
            AAPL · Nasdaq · SEC CIK {cashFlowStatement?.company.cik ?? "0000320193"}
          </p>
        </div>
      </header>

      {cashFlowStatement ? (
        <OperatingCashFlowLearning cashFlowStatement={cashFlowStatement} />
      ) : (
        <div className="data-empty-state profit-data-empty" role="status">
          <div className="data-empty-state__value" aria-hidden="true">—</div>
          <div>
            <strong>Operating Cash Flow data is not available yet</strong>
            <p>{dataError}</p>
            <p>
              FinPath will not replace missing or mismatched SEC facts with
              hard-coded cash-flow values.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
