import { lessonCatalog, type ConceptId } from "./lesson-catalog.ts";

export const LEARNING_PROGRESS_STORAGE_KEY = "finpath.learning-progress";
export const LEARNING_PROGRESS_VERSION = 1 as const;

export const conceptIds = lessonCatalog.map((lesson) => lesson.id);
export type { ConceptId } from "./lesson-catalog.ts";

export type LearningProgress = {
  version: typeof LEARNING_PROGRESS_VERSION;
  exploredConceptIds: ConceptId[];
};

export type ConceptProgressState = "explored" | "current" | "available";

export type StorageReader = Pick<Storage, "getItem">;
export type StorageWriter = Pick<Storage, "setItem">;

const knownConceptIds = new Set<string>(conceptIds);

export function createDefaultLearningProgress(): LearningProgress {
  return {
    version: LEARNING_PROGRESS_VERSION,
    exploredConceptIds: [],
  };
}

export function normalizeLearningProgress(value: unknown): LearningProgress {
  if (!value || typeof value !== "object") {
    return createDefaultLearningProgress();
  }

  const candidate = value as {
    version?: unknown;
    exploredConceptIds?: unknown;
  };

  if (
    candidate.version !== LEARNING_PROGRESS_VERSION ||
    !Array.isArray(candidate.exploredConceptIds)
  ) {
    return createDefaultLearningProgress();
  }

  const explored = new Set<ConceptId>();
  for (const conceptId of candidate.exploredConceptIds) {
    if (typeof conceptId === "string" && knownConceptIds.has(conceptId)) {
      explored.add(conceptId as ConceptId);
    }
  }

  return {
    version: LEARNING_PROGRESS_VERSION,
    exploredConceptIds: conceptIds.filter((conceptId) => explored.has(conceptId)),
  };
}

export function readLearningProgress(
  storage: StorageReader | null | undefined,
): LearningProgress {
  if (!storage) return createDefaultLearningProgress();

  try {
    const stored = storage.getItem(LEARNING_PROGRESS_STORAGE_KEY);
    if (!stored) return createDefaultLearningProgress();
    return normalizeLearningProgress(JSON.parse(stored));
  } catch {
    return createDefaultLearningProgress();
  }
}

export function writeLearningProgress(
  storage: StorageWriter | null | undefined,
  progress: LearningProgress,
): boolean {
  if (!storage) return false;

  try {
    storage.setItem(
      LEARNING_PROGRESS_STORAGE_KEY,
      JSON.stringify(normalizeLearningProgress(progress)),
    );
    return true;
  } catch {
    return false;
  }
}

export function markConceptsExplored(
  progress: LearningProgress,
  conceptIdsToMark: readonly ConceptId[],
): LearningProgress {
  const explored = new Set(progress.exploredConceptIds);
  conceptIdsToMark.forEach((conceptId) => explored.add(conceptId));
  return normalizeLearningProgress({
    version: LEARNING_PROGRESS_VERSION,
    exploredConceptIds: [...explored],
  });
}

export function deriveCurrentConcept(
  progress: LearningProgress,
): ConceptId | null {
  const explored = new Set(progress.exploredConceptIds);

  if (!explored.has("revenue")) return "revenue";
  if (!explored.has("revenue-growth")) return "revenue-growth";
  if (!explored.has("profit")) return "profit";
  if (!explored.has("net-profit-margin")) return "net-profit-margin";
  if (!explored.has("operating-cash-flow")) return "operating-cash-flow";
  if (!explored.has("investing-financing-cash-flow")) {
    return "investing-financing-cash-flow";
  }
  if (!explored.has("free-cash-flow")) return "free-cash-flow";
  return null;
}

export function deriveConceptState(
  conceptId: ConceptId,
  progress: LearningProgress,
): ConceptProgressState {
  const explored = new Set(progress.exploredConceptIds);
  if (explored.has(conceptId)) return "explored";

  const current = deriveCurrentConcept(progress);
  if (current === conceptId) return "current";
  return "available";
}

export type HomeRecommendation = {
  conceptId: ConceptId;
  title: string;
  goal: string;
  href: string;
  action: "Start" | "Continue" | "Review";
};

const recommendations: Record<ConceptId, Omit<HomeRecommendation, "conceptId" | "action">> = {
  revenue: {
    title: "Revenue",
    goal: "Understand Apple’s top line, then compare how Revenue changed year over year.",
    href: "/learn/company-analysis/revenue",
  },
  "revenue-growth": {
    title: "Revenue Growth",
    goal: "Compare Apple’s annual Revenue and calculate the change from the prior year.",
    href: "/learn/company-analysis/revenue-growth",
  },
  profit: {
    title: "Profit / Net Income",
    goal: "Follow Apple’s reported income-statement lines from Revenue to Net Income.",
    href: "/learn/company-analysis/profit",
  },
  "net-profit-margin": {
    title: "Net Profit Margin",
    goal: "Compare Net Income with Revenue using a simple $100 mental model.",
    href: "/learn/company-analysis/net-profit-margin",
  },
  "operating-cash-flow": {
    title: "Operating Cash Flow",
    goal: "See how Apple’s Net Income connects to cash generated by operating activities.",
    href: "/learn/company-analysis/operating-cash-flow",
  },
  "investing-financing-cash-flow": {
    title: "Investing & Financing Cash Flow",
    goal: "See how all three cash-flow sections connect to Apple’s change in cash.",
    href: "/learn/company-analysis/investing-financing-cash-flow",
  },
  "free-cash-flow": {
    title: "Free Cash Flow",
    goal: "Derive one simple Free Cash Flow measure from Apple’s reported cash-flow inputs.",
    href: "/learn/company-analysis/free-cash-flow",
  },
};

export function deriveHomeRecommendation(
  progress: LearningProgress,
): HomeRecommendation {
  const current = deriveCurrentConcept(progress);
  if (!current) {
    return {
      conceptId: "free-cash-flow",
      ...recommendations["free-cash-flow"],
      action: "Review",
    };
  }

  return {
    conceptId: current,
    ...recommendations[current],
    action: current === "revenue" ? "Start" : "Continue",
  };
}
