export const lessonCatalog = [
  {
    id: "revenue",
    number: 1,
    title: "Revenue",
    shortGoal: "Understand a company’s top line before costs and expenses.",
    href: "/learn/company-analysis/revenue",
  },
  {
    id: "revenue-growth",
    number: 2,
    title: "Revenue Growth",
    shortGoal: "Compare annual Revenue and calculate year-over-year change.",
    href: "/learn/company-analysis/revenue-growth",
  },
  {
    id: "profit",
    number: 3,
    title: "Profit / Net Income",
    shortGoal: "Follow reported costs and expenses from Revenue to Net Income.",
    href: "/learn/company-analysis/profit",
  },
  {
    id: "net-profit-margin",
    number: 4,
    title: "Net Profit Margin",
    shortGoal: "Put Net Income on a $100 Revenue scale.",
    href: "/learn/company-analysis/net-profit-margin",
  },
  {
    id: "operating-cash-flow",
    number: 5,
    title: "Operating Cash Flow",
    shortGoal: "Connect Net Income to cash generated by operating activities.",
    href: "/learn/company-analysis/operating-cash-flow",
  },
  {
    id: "investing-financing-cash-flow",
    number: 6,
    title: "Investing & Financing Cash Flow",
    shortGoal: "Connect all three cash-flow sections to the annual change in cash.",
    href: "/learn/company-analysis/investing-financing-cash-flow",
  },
  {
    id: "free-cash-flow",
    number: 7,
    title: "Free Cash Flow",
    shortGoal: "Derive one simple analytical measure from reported cash-flow inputs.",
    href: "/learn/company-analysis/free-cash-flow",
  },
  {
    id: "balance-sheet",
    number: 8,
    title: "Balance Sheet",
    shortGoal: "Read a company’s financial position at one reporting date.",
    href: "/learn/company-analysis/balance-sheet",
  },
  {
    id: "cash-and-debt",
    number: 9,
    title: "Cash & Debt",
    shortGoal: "Separate Cash, Borrowings and Total Liabilities at one reporting date.",
    href: "/learn/company-analysis/cash-and-debt",
  },
  {
    id: "three-statements-connect",
    number: 10,
    title: "Three Statements Connect",
    shortGoal: "Connect annual performance, cash movement and the reporting-date position.",
    href: "/learn/company-analysis/three-statements-connect",
  },
] as const;

export type ConceptId = (typeof lessonCatalog)[number]["id"];
export type LessonDefinition = (typeof lessonCatalog)[number];

export function getLesson(conceptId: ConceptId): LessonDefinition {
  const lesson = lessonCatalog.find((candidate) => candidate.id === conceptId);
  if (!lesson) throw new Error(`Unknown lesson: ${conceptId}`);
  return lesson;
}

export function getAdjacentLessons(conceptId: ConceptId): {
  previous: LessonDefinition | null;
  next: LessonDefinition | null;
} {
  const index = lessonCatalog.findIndex((lesson) => lesson.id === conceptId);
  if (index < 0) throw new Error(`Unknown lesson: ${conceptId}`);
  return {
    previous: lessonCatalog[index - 1] ?? null,
    next: lessonCatalog[index + 1] ?? null,
  };
}
